name: KaizenPortals
version: '${version}'
main: portals.portaltoexit.Portaltoexit
api-version: '1.21'
author: KaizenCore
description: Advanced portal plugin with multiple exit points and continuous improvements
website: https://github.com/KaizenCore/portal2exit
softdepend: [Vault]

commands:
  portal:
    description: Main portal command (basic functionality)
    usage: /portal
    permission: portal2exit.use

permissions:
  portal2exit.use:
    description: Allows basic portal usage
    default: true
  portal2exit.create:
    description: Allows creating portals
    default: true
  portal2exit.wand:
    description: Allows using the portal wand
    default: true
  portal2exit.gui:
    description: Allows using the portal GUI
    default: true
  portal2exit.admin:
    description: Allows admin commands and managing all portals
    default: op
